# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ContactDSM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ContactDSM
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

end
